Repository RCMartins/blinky, pull requests merged in 2020-05, with the labels that each got.

#89 Added --onlyMutateDiff parameter
  .travis.yml
  README.md
  bin/coursier
  blinky-cli/src/main/resources/scalafix
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/MutationsConfig.scala
  blinky-cli/src/main/scala/blinky/run/OptionsConfig.scala
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/SimpleBlinkyConfig.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/Utils.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/internal/Mutant.scala
  blinky-core/src/main/scala/blinky/v0/BlinkyConfig.scala
  examples/default/build.sbt
  examples/default/project/build.properties
  examples/default/project/plugins.sbt
  examples/example1/build.sbt
  examples/example2/.blinky.conf
  examples/example2/project/build.properties
  examples/example2/project/plugins.sbt
  examples/example3/.blinky.conf
  examples/example3/build.sbt
  examples/example3/project/build.properties
  examples/example3/project/plugins.sbt
  examples/example4/.blinky.conf
  examples/example4/startup.sh
  examples/example5/.blinky.conf
  examples/example5/build.sbt
  examples/example5/src/main/scala/Example.scala
  examples/example5/src/test/scala/ExampleTest.scala
  input/src/main/scala/test/All1.scala
  input/src/main/scala/test/ArithmeticOperators.scala
  input/src/main/scala/test/ConditionalExpressions1.scala
  input/src/main/scala/test/DisabledMutations.scala
  input/src/main/scala/test/GeneralSyntax1.scala
  input/src/main/scala/test/GeneralSyntax2.scala
  input/src/main/scala/test/GeneralSyntax3.scala
  input/src/main/scala/test/GeneralSyntax4.scala
  input/src/main/scala/test/GeneralSyntax5.scala
  input/src/main/scala/test/LiteralBooleans.scala
  input/src/main/scala/test/LiteralStrings.scala
  input/src/main/scala/test/MatchSyntax1.scala
  input/src/main/scala/test/ScalaOptions.scala
  input/src/main/scala/test/ScalaTry.scala
  input/src/main/scala/test/SubMutators1.scala
  input/src/main/scala/test/SubMutators2.scala
  input/src/main/scala/test/SubMutators3.scala
  input/src/main/scala/test/TermPlaceholder1.scala
  input/src/main/scala/test/UnaryOperations.scala
  travis/cli.blinky.conf
  travis/runCurrentVersion.sc
  travis/runExamples.sc
  travis/setup.sh
Labels: enhancement

#90 .mutants files are now unit tested
  .gitattributes
  .github/release-drafter.yml
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/BlinkyConfig.scala
  input/src/main/scala/test/All1.scala
  output/src/main/resources/test/All1.mutants
  tests/src/test/scala/fix/RuleSuite.scala
  travis/runExamples.sc
Labels: enhancement

#91 Use git diff in 'core' and move line number logic to 'cli'
  README.md
  blinky-cli/src/main/scala/blinky/run/Mutant.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/Utils.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/cli/TestSpec.scala
  blinky-cli/src/test/scala/blinky/cli/UtilsTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/internal/Mutant.scala
  build.sbt
  output/src/main/resources/test/All1.mutants
  tests/src/test/scala/fix/RuleSuite.scala
  travis/cli.blinky.conf
Labels: enhancement

#92 Created github-pages website for blinky
  .github/release-drafter.yml
  .travis.yml
  README.md
  blinky-docs/src/main/scala/docs/Main.scala
  build.sbt
  docs/configuration.md
  docs/installation.md
  docs/mutators.md
  project/plugins.sbt
  travis/core.blinky.conf
  travis/runCurrentVersion.sc
  website/.gitignore
  website/core/Footer.js
  website/package.json
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
Labels: docs

#93 Update scalafmt-core to 2.5.3
  .scalafmt.conf
Labels: chore

#94 Added more parser parameters & fixed default .blinky.conf logic
  .gitattributes
  .gitignore
  .scalafmt.conf
  .travis.yml
  blinky-cli/src/main/scala/blinky/cli/Cli.scala
  blinky-cli/src/main/scala/blinky/run/Args.scala
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/MutationsConfig.scala
  blinky-cli/src/main/scala/blinky/run/MutationsConfigValidated.scala
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/SimpleBlinkyConfig.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/Utils.scala
  blinky-cli/src/test/resources/.blinky.conf
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  blinky-core/src/main/scala/blinky/v0/BlinkyConfig.scala
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  blinky-core/src/main/scala/blinky/v0/Mutators.scala
  blinky-core/src/test/scala/blinky/v0/MutatorsTest.scala
  blinky-core/src/test/scala/blinky/v0/TestSpec.scala
  build.sbt
  tests/src/test/scala/fix/RuleSuite.scala
  travis/core.blinky.conf
  travis/runCurrentVersion.sc
  travis/runExamples.sc
  travis/setup.sh
  travis/utils.sc
Labels: enhancement

#95 Added new mutator for interpolated strings
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  blinky-core/src/test/scala/blinky/v0/BlinkyConfigTest.scala
  docs/mutators.md
  input/src/main/scala/test/LiteralStrings.scala
  input/src/main/scala/test/SubMutators3.scala
  output/src/main/scala/test/LiteralStrings.scala
  tests/src/test/scala/fix/RuleSuite.scala
  travis/cli.blinky.conf
  travis/core.blinky.conf
  travis/runCurrentVersion.sc
Labels: enhancement

#98 Replaced codacy with coveralls
  .travis.yml
  README.md
  project/plugins.sbt
Labels: chore

#97 new Collections mutators
  .scalafmt.conf
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  docs/mutators.md
  input/src/main/scala/test/Collections1.scala
  input/src/main/scala/test/GeneralSyntax3.scala
  input/src/main/scala/test/SubMutators3.scala
  output/src/main/scala/test/Collections1.scala
  output/src/main/scala/test/GeneralSyntax3.scala
  travis/core.blinky.conf
Labels: enhancement

#99 Added tests to ConsoleReporter
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/test/scala/blinky/TestSpec.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/cli/TestSpec.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/UtilsTest.scala
  build.sbt
  examples/example2/.blinky.conf
Labels: enhancement

#100 Some refactoring in cli
  blinky-cli/src/main/scala/blinky/cli/Cli.scala
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  build.sbt
  travis/cli.blinky.conf
Labels: chore
