Repository RCMartins/blinky, pull requests merged in 2020-06, with the labels that each got.

#106 Added PartialFunction mutator
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  blinky-core/src/main/scala/blinky/v0/ReplaceType.scala
  docs/mutators.md
  input/src/main/scala/test/PartialFunctionsMutators1.scala
  input/src/main/scala/test/PartialFunctionsSyntax1.scala
  output/src/main/scala/test/PartialFunctionsMutators1.scala
  output/src/main/scala/test/PartialFunctionsSyntax1.scala
  travis/cli.blinky.conf
Labels: enhancement

#107 testing improvements [blinky-full]
  .gitignore
  .travis.yml
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  build.sbt
  input/src/main/scala/test/LiteralStrings.scala
  input/src/main/scala/test/NoFilesToMutate.scala
  input/src/main/scala/test/PartialFunctionsMutators1.scala
  output/src/main/scala-output/test/All1.scala
  output/src/main/scala-output/test/ArithmeticOperators.scala
  output/src/main/scala-output/test/Collections1.scala
  output/src/main/scala-output/test/ConditionalExpressions1.scala
  output/src/main/scala-output/test/DisabledMutations.scala
  output/src/main/scala-output/test/GeneralSyntax1.scala
  output/src/main/scala-output/test/GeneralSyntax2.scala
  output/src/main/scala-output/test/GeneralSyntax3.scala
  output/src/main/scala-output/test/GeneralSyntax4.scala
  output/src/main/scala-output/test/GeneralSyntax5.scala
  output/src/main/scala-output/test/LiteralBooleans.scala
  output/src/main/scala-output/test/LiteralStrings.scala
  output/src/main/scala-output/test/MatchSyntax1.scala
  output/src/main/scala-output/test/MatchSyntax2.scala
  output/src/main/scala-output/test/NoFilesToMutate.scala
  output/src/main/scala-output/test/PartialFunctionsMutators1.scala
  output/src/main/scala-output/test/PartialFunctionsSyntax1.scala
  output/src/main/scala-output/test/ScalaOptions.scala
  output/src/main/scala-output/test/ScalaTry.scala
  output/src/main/scala-output/test/SubMutators1.scala
  output/src/main/scala-output/test/SubMutators2.scala
  output/src/main/scala-output/test/SubMutators3.scala
  output/src/main/scala-output/test/TermPlaceholder1.scala
  output/src/main/scala-output/test/UnaryOperations.scala
  project/PreProcess.scala
  project/build.sbt
  tests/src/test/scala/fix/RuleSuite.scala
  travis/cli.blinky.conf
  travis/core.blinky.conf
  travis/runCurrentVersion.sc
Labels: chore

#108 Added new mutator - PartialFunctions.RemoveOneAlternative
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  docs/mutators.md
  input/src/main/scala/test/PartialFunctionsMutators2.scala
  input/src/main/scala/test/SubMutators3.scala
  output/src/main/scala-output/test/PartialFunctionsMutators2.scala
Labels: enhancement

#109 Added new mutator - ScalaStrings.Trim
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  docs/mutators.md
  input/src/main/scala/test/StringMutator.scala
  input/src/main/scala/test/SubMutators3.scala
  output/src/main/scala-output/test/StringMutator.scala
Labels: enhancement

#110 Implemented ZIO in Cli
  blinky-cli/src/main/resources/coursier
  blinky-cli/src/main/scala/blinky/cli/Cli.scala
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/config/Args.scala
  blinky-cli/src/main/scala/blinky/run/config/MutationsConfig.scala
  blinky-cli/src/main/scala/blinky/run/config/MutationsConfigValidated.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/main/scala/blinky/run/config/SimpleBlinkyConfig.scala
  blinky-cli/src/main/scala/blinky/run/external/AmmoniteExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/modules/CliModule.scala
  blinky-cli/src/main/scala/blinky/run/modules/ExternalModule.scala
  blinky-cli/src/main/scala/blinky/run/modules/ParserModule.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
  blinky-cli/src/test/scala/blinky/TestSpec.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/UtilsTest.scala
  blinky-cli/src/test/scala/blinky/run/modules/TestModules.scala
  build.sbt
  project/SBTDefaults.scala
  travis/cli.blinky.conf
Labels: chore

#113 Added --multiRun parameter
  .travis.yml
  blinky-cli/src/main/scala/blinky/cli/Cli.scala
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/config/MutationsConfig.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/test/resources/options1.conf
  blinky-cli/src/test/resources/wrongMultiRun.conf
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  docs/configuration.md
Labels: enhancement

#114 Update sbt-bloop to 1.4.2
  examples/default/project/plugins.sbt
  project/plugins.sbt
Labels: chore

#116 Update scalafmt-core to 2.6.1
  .scalafmt.conf
Labels: chore

#118 Fixed typo in message when using --onlyMutateDiff flag
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
Labels: bug

#119 Update scalatest to 3.2.0
  build.sbt
  examples/default/build.sbt
  examples/example1/src/test/scala/ExampleTest.scala
  examples/example2/src/test/scala/ExampleTest.scala
  examples/example3/src/test/scala/ExampleTest.scala
  examples/example4/src/test/scala/ExampleTest.scala
  examples/example5/build.sbt
  examples/example5/src/test/scala/ExampleTest.scala
Labels: chore

#121 Fixed blinky bug [blinky-full]
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/external/AmmoniteExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  travis/cli.blinky.conf
Labels: bug

#120 Fixed bug in FindMutations
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  examples/example6/.blinky.conf
  examples/example6/build.sbt
  examples/example6/src/main/scala/Example.scala
  examples/example6/src/test/scala/ExampleTest.scala
  input/src/main/scala/test/LiteralStrings.scala
  output/src/main/scala-output/test/LiteralStrings.scala
  travis/runExamples.sc
Labels: bug

#122 Update bloop to 1.4.3
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-docs/src/main/scala/docs/Main.scala
  docs/installation.md
  examples/default/project/plugins.sbt
  examples/example6/build.sbt
  project/plugins.sbt
Labels: chore

#123 Improved TestMutationsBloop message [blinky-full]
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
Labels: enhancement
