Repository RCMartins/blinky, pull requests merged in 2021-03, with the labels that each got.

#197 Updated semanticdb version / added tests to cli.Setup
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/test/scala/blinky/run/SetupTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  build.sbt
  ci-tests/cli.blinky.conf
Labels: chore

#198 Fixed issue when working on large codebases
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/external/AmmoniteExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
Labels: bug

#200 Added extra checks when copying project files
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/external/AmmoniteExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
Labels: enhancement

#201 Update scopt to 4.0.1
  build.sbt
Labels: chore

#205 Update zio, zio-test, zio-test-sbt to 1.0.5
  build.sbt
Labels: chore

#207 Update scalatest to 3.2.6
  build.sbt
  ci-tests/examples/default/build.sbt
  ci-tests/examples/example5/build.sbt
  ci-tests/examples/example6/build.sbt
  ci-tests/examples/example7/build.sbt
Labels: chore

#204 Update sbt-ci-release to 1.5.6
  .github/workflows/release.yml
  project/plugins.sbt
Labels: chore

#206 Update sbt to 1.4.9
  ci-tests/examples/default/project/build.properties
  project/build.properties
Labels: chore

#208 Fixed release script
  .github/scripts/setup.sh
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: chore

#211 Added new parameter to only test specific mutants
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/test/resources/options1.conf
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/BlinkyConfig.scala
  blinky-core/src/main/scala/blinky/v0/MutantRange.scala
  blinky-core/src/test/scala/blinky/internal/BlinkyTest.scala
  blinky-core/src/test/scala/blinky/v0/BlinkyConfigTest.scala
  blinky-core/src/test/scala/blinky/v0/MutantRangeTest.scala
  docs/configuration.md
  input/src/main/scala/test/SpecificMutantIndices.scala
  output/src/main/scala-output/test/SpecificMutantIndices.scala
Labels: enhancement

#212 Added --testInOrder parameter
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/test/resources/options1.conf
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  docs/configuration.md
Labels: enhancement

#214 Added smart file matches for --filesToMutate parameter
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/config/FileFilter.scala
  blinky-cli/src/main/scala/blinky/run/config/MutationsConfigValidated.scala
  blinky-cli/src/main/scala/blinky/run/external/AmmoniteExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  ci-tests/examples/example9/.blinky.conf
  ci-tests/examples/example9/build.sbt
  ci-tests/examples/example9/src/main/scala/Example.scala
  ci-tests/examples/example9/src/test/scala/ExampleTest.scala
Labels: enhancement

#215 Improved examples CI job
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  ci-tests/examples/example1/result.txt
  ci-tests/examples/example2/result.txt
  ci-tests/examples/example3/result.txt
  ci-tests/examples/example4/disabled
  ci-tests/examples/example4/result.txt
  ci-tests/examples/example5/result.txt
  ci-tests/examples/example6/result.txt
  ci-tests/examples/example7/result.txt
  ci-tests/examples/example8/result.txt
  ci-tests/examples/example9/.blinky.conf
  ci-tests/examples/example9/build.sbt
  ci-tests/examples/example9/result.txt
  project/RunExamples.scala
Labels: chore

#216 Added new ci job to test community scala projects
  .github/workflows/pr.yml
  build.sbt
  project/RunCommunityProjects.scala
  project/RunExamples.scala
Labels: chore

#218 Update sbt-mdoc to 2.2.19
  project/plugins.sbt
Labels: chore

#219 Fixed --filesToMutate bug
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/external/AmmoniteExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  ci-tests/examples/example10/.blinky.conf
  ci-tests/examples/example10/result.txt
  ci-tests/examples/example10/src/main/scala/Example.scala
  ci-tests/examples/example10/src/test/scala/ExampleTest.scala
  ci-tests/examples/example10/startup.sh
Labels: bug
