Repository RCMartins/blinky, pull requests merged in 2022-07, with the labels that each got.

#360 Added mutators for ForYield term
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  input/src/main/scala/test/GeneralForYield.scala
  output/src/main/scala-output/test/GeneralForYield.scala
Labels: enhancement

#357 Update zio to 2.0.0
  .github/release-drafter.yml
  blinky-cli/src/main/scala/blinky/cli/Cli.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Utils.scala
  blinky-cli/src/main/scala/blinky/run/modules/CliModule.scala
  blinky-cli/src/main/scala/blinky/run/modules/ExternalModule.scala
  blinky-cli/src/main/scala/blinky/run/modules/ParserModule.scala
  blinky-cli/src/main/scala/blinky/run/modules/package.scala
  blinky-cli/src/test/scala/blinky/TestSpec.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  blinky-cli/src/test/scala/blinky/run/SetupTest.scala
  blinky-cli/src/test/scala/blinky/run/UtilsTest.scala
  blinky-cli/src/test/scala/blinky/run/config/OptionsConfigTest.scala
  blinky-cli/src/test/scala/blinky/run/modules/TestModules.scala
  build.sbt
Labels: chore

#358 Improved handling of timeouts
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/TimeoutResult.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/OSExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  blinky-cli/src/test/scala/blinky/run/SetupTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  ci-tests/examples/example01/.blinky.conf
  ci-tests/examples/example01/result.txt
  ci-tests/examples/example01/src/main/scala/Example.scala
  ci-tests/examples/example01/src/test/scala/ExampleTest.scala
  ci-tests/examples/example02/.blinky.conf
  ci-tests/examples/example02/result.txt
  ci-tests/examples/example02/src/main/scala/Example.scala
  ci-tests/examples/example02/src/test/scala/ExampleTest.scala
  ci-tests/examples/example03/.blinky.conf
  ci-tests/examples/example03/result.txt
  ci-tests/examples/example03/src/main/scala/example/Example.scala
  ci-tests/examples/example03/src/main/scala/example/Utils.scala
  ci-tests/examples/example03/src/test/scala/ExampleTest.scala
  ci-tests/examples/example04/.blinky.conf
  ci-tests/examples/example04/result.txt
  ci-tests/examples/example04/src/main/scala/example/Example.scala
  ci-tests/examples/example04/src/main/scala/example/Utils.scala
  ci-tests/examples/example04/src/test/scala/ExampleTest.scala
  ci-tests/examples/example04/startup.sh
  ci-tests/examples/example05/.blinky.conf
  ci-tests/examples/example05/build.sbt
  ci-tests/examples/example05/result.txt
  ci-tests/examples/example05/src/main/scala/Example.scala
  ci-tests/examples/example05/src/test/scala/ExampleTest.scala
  ci-tests/examples/example06/.blinky.conf
  ci-tests/examples/example06/build.sbt
  ci-tests/examples/example06/result.txt
  ci-tests/examples/example06/src/main/scala/Example.scala
  ci-tests/examples/example06/src/test/scala/ExampleTest.scala
  ci-tests/examples/example07/.blinky.conf
  ci-tests/examples/example07/build.sbt
  ci-tests/examples/example07/result.txt
  ci-tests/examples/example07/src/main/scala/Example.scala
  ci-tests/examples/example07/src/test/scala/ExampleTest.scala
  ci-tests/examples/example08/.blinky.conf
  ci-tests/examples/example08/result.txt
  ci-tests/examples/example08/src/main/scala/Example.scala
  ci-tests/examples/example08/src/test/scala/ExampleTest.scala
  ci-tests/examples/example09/.blinky.conf
  ci-tests/examples/example09/result.txt
  ci-tests/examples/example09/src/main/scala/Example.scala
  ci-tests/examples/example09/src/test/scala/ExampleTest.scala
  project/RunCommunityProjects.scala
  project/RunCurrentVersion.scala
  project/RunExamples.scala
Labels: bug

#361 Added more mutators for String
  blinky-core/src/main/scala/blinky/v0/mutators/ArithmeticOperators.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaStrings.scala
  docs/mutators.md
  input/src/main/scala/test/StringMutator.scala
  input/src/main/scala/test/SubMutatorsAll.scala
  output/src/main/scala-output/test/StringMutator.scala
  output/src/main/scala-output/test/SubMutators3.scala
  output/src/main/scala-output/test/SubMutatorsAll.scala
Labels: enhancement

#362 Updated codecov, sbt & README links
  .github/workflows/ci.yml
  README.md
  codecov.yml
  docs/installation.md
  project/build.properties
  project/plugins.sbt
Labels: chore, docs

#363 Update sbt-bloop to 1.5.2
  project/plugins.sbt
Labels: chore

#365 Moved string reverse mutator from Collections to String
  blinky-core/src/main/scala/blinky/v0/mutators/Collections.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaStrings.scala
  blinky-core/src/test/scala/blinky/v0/MutatorTest.scala
  docs/mutators.md
  input/src/main/scala/test/CollectionsReverse.scala
  input/src/main/scala/test/StringMutator.scala
  input/src/main/scala/test/SubMutatorsAll.scala
  output/src/main/scala-output/test/CollectionsReverse.scala
  output/src/main/scala-output/test/StringMutator.scala
Labels: enhancement, docs

#366 Removed old setup hack
  .github/scripts/setup.sh
Labels: chore

#367 Added mutator for take/drop on collections and strings
  blinky-core/src/main/scala/blinky/v0/mutators/Collections.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaStrings.scala
  docs/mutators.md
  input/src/main/scala/test/CollectionsDropTake.scala
  input/src/main/scala/test/StringMutator.scala
  input/src/main/scala/test/SubMutatorsAll.scala
  output/src/main/scala-output/test/CollectionsDropTake.scala
  output/src/main/scala-output/test/StringMutator.scala
Labels: enhancement, docs

#368 Update scopt to 4.1.0
  build.sbt
Labels: chore

#370 Update sbt-scoverage to 2.0.0
  project/plugins.sbt
Labels: chore
