Repository RCMartins/blinky, pull requests merged in 2022-06, with the labels that each got.

#353 Update sbt to 1.6.2
  ci-tests/examples/default/project/build.properties
  project/build.properties
Labels: chore

#226 Added new mutator for "if" control flow
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  ci-tests/examples/example8/.blinky.conf
  ci-tests/examples/example8/result.txt
  ci-tests/examples/example8/src/main/scala/Example.scala
  docs/mutators.md
  input/src/main/scala/test/ScalaIf.scala
  input/src/main/scala/test/SubMutators3.scala
  output/src/main/scala-output/test/ScalaIf.scala
Labels: enhancement

#209 Updated Scala to 2.13
  .github/workflows/pr.yml
  README.md
  blinky-cli/src/main/resources/scalafix
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/Utils.scala
  blinky-cli/src/main/scala/blinky/run/config/FileFilter.scala
  blinky-cli/src/main/scala/blinky/run/config/MutationsConfigValidated.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/main/scala/blinky/run/external/ExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/external/OSExternalCalls.scala
  blinky-cli/src/main/scala/blinky/run/modules/ExternalModule.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  blinky-cli/src/test/scala/blinky/run/SetupTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  blinky-cli/src/test/scala/blinky/run/UtilsTest.scala
  blinky-cli/src/test/scala/blinky/run/config/OptionsConfigTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/v0/BlinkyConfig.scala
  blinky-core/src/main/scala/blinky/v0/Mutators.scala
  build.sbt
  ci-tests/cli.blinky.conf
  ci-tests/examples/default/project/plugins.sbt
  docs/configuration.md
  docs/installation.md
  input/src/main/scala/test/LiteralStrings.scala
  output/src/main/scala-output/test/LiteralStrings.scala
  output/src/main/scala-output/test/PartialFunctionsMutators1.scala
  output/src/main/scala-output/test/PartialFunctionsMutators2.scala
  project/RunCommunityProjects.scala
  project/RunCurrentVersion.scala
  project/RunExamples.scala
  project/SBTDefaults.scala
  project/build.sbt
  project/plugins.sbt
Labels: chore

#356 Updated autolabeler workflow
  .github/release-drafter.yml
Labels: chore

#348 Update quicklens to 1.8.8
  build.sbt
Labels: chore

#349 Update scalafmt-core to 3.5.3
  .scalafmt.conf
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/external/OSExternalCalls.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  build.sbt
  input/src/main/scala/test/TermPlaceholder1.scala
  input/src/main/scala/test/TermPlaceholder2.scala
  output/src/main/resources/test/TermPlaceholder1.mutants
  output/src/main/scala-output/test/TermPlaceholder1.scala
  output/src/main/scala-output/test/TermPlaceholder2.scala
Labels: chore

#346 Update scalatest to 3.2.12
  build.sbt
  ci-tests/examples/default/build.sbt
  ci-tests/examples/example5/build.sbt
  ci-tests/examples/example6/build.sbt
  ci-tests/examples/example7/build.sbt
Labels: chore

#359 Added Mutators to (char 'op' int) terms
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ArithmeticOperators.scala
  blinky-core/src/main/scala/blinky/v0/mutators/Collections.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ConditionalExpressions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ControlFlow.scala
  blinky-core/src/main/scala/blinky/v0/mutators/LiteralStrings.scala
  blinky-core/src/main/scala/blinky/v0/mutators/PartialFunctions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaOptions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaStrings.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaTry.scala
  blinky-core/src/test/scala/blinky/v0/MutatorTest.scala
  docs/mutators.md
  input/src/main/scala/test/ArithmeticOperators.scala
  input/src/main/scala/test/SubMutators3.scala
  output/src/main/scala-output/test/ArithmeticOperators.scala
Labels: enhancement, docs
