Repository RCMartins/blinky, pull requests merged in 2023-05, with the labels that each got.

#429 Update quicklens to 1.9.3
  build.sbt
Labels: chore

#428 Update sbt-ci-release to 1.5.12
  project/plugins.sbt
Labels: chore

#420 Update sbt-scalafix, scalafix-core to 0.10.4
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  output/src/main/resources/test/TermPlaceholder1.mutants
  output/src/main/scala-output/test/GeneralForYield.scala
  output/src/main/scala-output/test/TermPlaceholder1.scala
  project/SBTDefaults.scala
  project/plugins.sbt
Labels: bug, chore

#430 Added mutator for reduceOption on collections
  blinky-core/src/main/scala/blinky/v0/mutators/ArithmeticOperators.scala
  blinky-core/src/main/scala/blinky/v0/mutators/Collections.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ConditionalExpressions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ControlFlow.scala
  blinky-core/src/main/scala/blinky/v0/mutators/LiteralStrings.scala
  blinky-core/src/main/scala/blinky/v0/mutators/PartialFunctions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaOptions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaStrings.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaTry.scala
  docs/mutators.md
  input/src/main/scala/test/CollectionsReduce.scala
  output/src/main/scala-output/test/CollectionsReduce.scala
Labels: enhancement, docs

#431 Added mutator for when/unless on ZIO expressions
  .scalafmt.conf
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ZIO.scala
  build.sbt
  docs/maintenance.md
  docs/mutators.md
  input/src/main/scala/test/SubMutatorsAll.scala
  input/src/main/scala/test/zio/ZIOConditionalFilters.scala
  output/src/main/scala-output/test/zio/ZIOConditionalFilters.scala
  project/PreProcess.scala
  website/core/Footer.js
  website/sidebars.json
Labels: chore, docs

#432 Bug - Don't add mutations to java annotations
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  input/src/main/scala/test/JavaAnnotations.scala
  input/src/main/scala/test/general/ClassConstructors.scala
  input/src/main/scala/test/general/GeneralSyntax1.scala
  input/src/main/scala/test/general/GeneralSyntax2.scala
  input/src/main/scala/test/general/GeneralSyntax3.scala
  input/src/main/scala/test/general/GeneralSyntax4.scala
  input/src/main/scala/test/general/GeneralSyntax5.scala
  output/src/main/scala-output/test/JavaAnnotations.scala
  output/src/main/scala-output/test/general/ClassConstructors.scala
  output/src/main/scala-output/test/general/GeneralSyntax1.scala
  output/src/main/scala-output/test/general/GeneralSyntax2.scala
  output/src/main/scala-output/test/general/GeneralSyntax3.scala
  output/src/main/scala-output/test/general/GeneralSyntax4.scala
  output/src/main/scala-output/test/general/GeneralSyntax5.scala
Labels: bug

#433 Bug - Don't add mutations to java annotations - part 2
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  input/src/main/scala/test/JavaAnnotations.scala
  output/src/main/scala-output/test/JavaAnnotations.scala
Labels: bug

#437 Update sbt to 1.8.3
  ci-tests/examples/default/project/build.properties
  project/build.properties
Labels: chore
