Repository RCMartins/blinky, pull requests merged in 2023-06, with the labels that each got.

#444 Update sbt-scoverage to 2.0.8
  project/plugins.sbt
Labels: chore

#439 Update zio, zio-test, zio-test-sbt to 2.0.14
  build.sbt
Labels: chore

#441 Update scalafmt-core to 3.7.4
  .scalafmt.conf
Labels: chore

#443 Update sbt-scalafix to 0.11.0
  blinky-cli/src/main/resources/scalafix
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/test/scala/blinky/run/SetupTest.scala
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ArithmeticOperators.scala
  blinky-core/src/main/scala/blinky/v0/mutators/Collections.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ConditionalExpressions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ControlFlow.scala
  blinky-core/src/main/scala/blinky/v0/mutators/PartialFunctions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaOptions.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaStrings.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ScalaTry.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ZIO.scala
  build.sbt
  ci-tests/examples/default/build.sbt
  ci-tests/examples/example05/build.sbt
  ci-tests/examples/example06/build.sbt
  ci-tests/examples/example07/build.sbt
  docs/maintenance.md
  output/src/main/scala-output/test/GeneralForYield.scala
  output/src/main/scala-output/test/TermPlaceholder1.scala
  project/SBTDefaults.scala
  project/plugins.sbt
Labels: bug, chore, docs

#445 Updated docs and scala steward
  .scala-steward.conf
  README.md
Labels: docs

#447 Added Mutator Prepend on Collections
  blinky-core/src/main/scala/blinky/v0/mutators/Collections.scala
  docs/mutators.md
  input/src/main/scala/test/CollectionsPrepend.scala
  input/src/main/scala/test/SubMutatorsAll.scala
  output/src/main/scala-output/test/CollectionsPrepend.scala
Labels: enhancement, docs

#448 Update zio, zio-test, zio-test-sbt to 2.0.15
  build.sbt
Labels: chore

#449 Removed limitation on some if expressions
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  input/src/main/scala/test/ScalaIf2.scala
  output/src/main/scala-output/test/ScalaIf2.scala
Labels: bug

#451 Added a check for broken links in docs
  .github/workflows/pr.yml
  build.sbt
  docs/mutators.md
Labels: chore

#452 Fixed bug with PartialFunctions.RemoveOneCase mutator
  blinky-core/src/main/scala/blinky/v0/ReplaceType.scala
  blinky-core/src/main/scala/blinky/v0/mutators/PartialFunctions.scala
  docs/mutators.md
  input/src/main/scala/test/PartialFunctionsMutators3.scala
  input/src/main/scala/test/SubMutatorsAll.scala
  output/src/main/scala-output/test/PartialFunctionsMutators1.scala
  output/src/main/scala-output/test/PartialFunctionsMutators3.scala
Labels: bug, docs

#438 Update scalatest to 3.2.16
  build.sbt
  ci-tests/examples/default/build.sbt
  ci-tests/examples/example05/build.sbt
  ci-tests/examples/example06/build.sbt
  ci-tests/examples/example07/build.sbt
Labels: chore

#454 Replaced scalatest with zio test in core module
  blinky-core/src/test/scala/blinky/TestSpec.scala
  blinky-core/src/test/scala/blinky/internal/BlinkyTest.scala
  blinky-core/src/test/scala/blinky/v0/BlinkyConfigTest.scala
  blinky-core/src/test/scala/blinky/v0/MutantRangeTest.scala
  blinky-core/src/test/scala/blinky/v0/MutatorTest.scala
  blinky-core/src/test/scala/blinky/v0/MutatorsTest.scala
  build.sbt
Labels: chore

#453 Added new parameter 'testRunner' and added sbt support
  .sbtopts
  blinky-cli/src/main/scala/blinky/cli/Cli.scala
  blinky-cli/src/main/scala/blinky/run/ConsoleReporter.scala
  blinky-cli/src/main/scala/blinky/run/Instruction.scala
  blinky-cli/src/main/scala/blinky/run/Interpreter.scala
  blinky-cli/src/main/scala/blinky/run/MutationsRunner.scala
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/PrettyDiff.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/RunMutations.scala
  blinky-cli/src/main/scala/blinky/run/RunMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/RunMutationsSBT.scala
  blinky-cli/src/main/scala/blinky/run/Setup.scala
  blinky-cli/src/main/scala/blinky/run/TestMutationsBloop.scala
  blinky-cli/src/main/scala/blinky/run/Utils.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/main/scala/blinky/run/config/TestRunnerType.scala
  blinky-cli/src/main/scala/blinky/run/package.scala
  blinky-cli/src/test/resources/mutants/blinky-empty.mutants
  blinky-cli/src/test/resources/mutants/blinky1.mutants
  blinky-cli/src/test/resources/options1.conf
  blinky-cli/src/test/resources/wrongTestRunner.conf
  blinky-cli/src/test/scala/blinky/TestSpec.scala
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/PrettyDiffTest.scala
  blinky-cli/src/test/scala/blinky/run/RunMutationsBloopTest.scala
  blinky-cli/src/test/scala/blinky/run/RunMutationsSBTTest.scala
  blinky-cli/src/test/scala/blinky/run/RunMutationsTest.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  blinky-cli/src/test/scala/blinky/run/SetupTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  blinky-cli/src/test/scala/blinky/run/UtilsTest.scala
  blinky-cli/src/test/scala/blinky/run/config/OptionsConfigTest.scala
  build.sbt
  ci-tests/cli.blinky.conf
  ci-tests/examples/default/project/plugins.sbt
  ci-tests/examples/example11/.blinky.conf
  ci-tests/examples/example11/result.txt
  ci-tests/examples/example11/src/main/scala/Example.scala
  ci-tests/examples/example11/src/test/scala/ExampleTest.scala
  docs/configuration.md
  docs/maintenance.md
  project/RunCurrentVersion.scala
Labels: enhancement, chore, docs

#455 Added new option 'mainBranch'
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/test/resources/options1.conf
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/run/ConsoleReporterTest.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  docs/configuration.md
  project/RunExamples.scala
Labels: enhancement, docs

#457 Fixed tests in CI
  blinky-core/src/main/scala/blinky/internal/Blinky.scala
  blinky-core/src/main/scala/blinky/internal/FindMutations.scala
  ci-tests/cli.blinky.conf
  ci-tests/core.blinky.conf
  project/RunCurrentVersion.scala
Labels: chore

#456 Added new option 'copyGitFolder'
  blinky-cli/src/main/scala/blinky/run/Parser.scala
  blinky-cli/src/main/scala/blinky/run/Run.scala
  blinky-cli/src/main/scala/blinky/run/config/OptionsConfig.scala
  blinky-cli/src/test/resources/options1.conf
  blinky-cli/src/test/scala/blinky/cli/CliTest.scala
  blinky-cli/src/test/scala/blinky/run/RunTest.scala
  blinky-cli/src/test/scala/blinky/run/TestInstruction.scala
  docs/configuration.md
Labels: enhancement, docs

#458 Changed default branch to 'main'
  .github/scripts/setup.sh
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  README.md
  ci-tests/cli.blinky.conf
  ci-tests/core.blinky.conf
  docs/configuration.md
Labels: chore, docs

#460 Added new mutator 'ZIO.ForYield'
  blinky-core/src/main/scala/blinky/v0/Mutator.scala
  blinky-core/src/main/scala/blinky/v0/mutators/ZIO.scala
  docs/mutators.md
  input/src/main/scala/test/SubMutatorsAll.scala
  input/src/main/scala/test/zio/ZIOForYield1.scala
  input/src/main/scala/test/zio/ZIOForYield2.scala
  output/src/main/scala-output/test/zio/ZIOForYield1.scala
  output/src/main/scala-output/test/zio/ZIOForYield2.scala
Labels: enhancement, docs

#461 Update sbt to 1.9.1
  ci-tests/examples/default/project/build.properties
  project/build.properties
Labels: chore
